name: Update with the latest base16 colorschemes
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v3
      - name: Fetch the schemes repository
        uses: actions/checkout@v3
        with:
          repository: base16-project/base16-schemes
          path: schemes
      - name: Update schemes
        uses: base16-project/base16-builder-go@latest
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update with the latest base16-project colorschemes
          branch: ${{ github.head_ref }}
          commit_user_name: base16-project-bot
          commit_user_email: base16themeproject@proton.me
          commit_author: base16-project-bot <base16themeproject@proton.me>
